# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'
use_frameworks!

target 'rainyshinycloudy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #inherit! :search_paths
    # Pods for rainyshinycloudy
    pod 'Alamofire', '~> 4.4'
  end
  # Pods for testing
